name: twaindsm
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0-93.0.dev <3.0.0' # ffi: ^1.0.0 required

dependencies:
  ffi: ^1.0.0
  convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  ffigen: ^2.4.2

ffigen:
  name: TwainDsm
  description: Bindings to `twain.h`.
  output: 'lib/twaindsm.dart'
  headers:
    entry-points:
      - 'twaindsm/twain.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**twain.h'