name: twaindsm
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^1.2.0

ffigen:
  name: TwainDsm
  description: Bindings to `twain.h`.
  output: 'lib/twaindsm.dart'
  headers:
    entry-points:
      - 'twaindsm/twain.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**twain.h'