// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class RGBQUAD extends ffi.Struct {
  @ffi.Uint8()
  int rgbBlue;

  @ffi.Uint8()
  int rgbGreen;

  @ffi.Uint8()
  int rgbRed;

  @ffi.Uint8()
  int rgbReserved;
}

class BITMAPINFOHEADER extends ffi.Struct {
  @ffi.Uint32()
  int biSize;

  @ffi.Int32()
  int biWidth;

  @ffi.Int32()
  int biHeight;

  @ffi.Uint16()
  int biPlanes;

  @ffi.Uint16()
  int biBitCount;

  @ffi.Uint32()
  int biCompression;

  @ffi.Uint32()
  int biSizeImage;

  @ffi.Int32()
  int biXPelsPerMeter;

  @ffi.Int32()
  int biYPelsPerMeter;

  @ffi.Uint32()
  int biClrUsed;

  @ffi.Uint32()
  int biClrImportant;
}
