// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `twain.h`.
class TwainDsm {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  TwainDsm(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  int DSM_Entry(
    ffi.Pointer<TW_IDENTITY> pOrigin,
    ffi.Pointer<TW_IDENTITY> pDest,
    int DG,
    int DAT,
    int MSG,
    ffi.Pointer<ffi.Void> pData,
  ) {
    return (_DSM_Entry ??=
        _dylib.lookupFunction<_c_DSM_Entry, _dart_DSM_Entry>('DSM_Entry'))(
      pOrigin,
      pDest,
      DG,
      DAT,
      MSG,
      pData,
    );
  }

  _dart_DSM_Entry? _DSM_Entry;

  int DS_Entry(
    ffi.Pointer<TW_IDENTITY> pOrigin,
    int DG,
    int DAT,
    int MSG,
    ffi.Pointer<ffi.Void> pData,
  ) {
    return (_DS_Entry ??=
        _dylib.lookupFunction<_c_DS_Entry, _dart_DS_Entry>('DS_Entry'))(
      pOrigin,
      DG,
      DAT,
      MSG,
      pData,
    );
  }

  _dart_DS_Entry? _DS_Entry;

  int TWAIN_Callback(
    ffi.Pointer<TW_IDENTITY> pOrigin,
    ffi.Pointer<TW_IDENTITY> pDest,
    int DG,
    int DAT,
    int MSG,
    ffi.Pointer<ffi.Void> pData,
  ) {
    return (_TWAIN_Callback ??=
        _dylib.lookupFunction<_c_TWAIN_Callback, _dart_TWAIN_Callback>(
            'TWAIN_Callback'))(
      pOrigin,
      pDest,
      DG,
      DAT,
      MSG,
      pData,
    );
  }

  _dart_TWAIN_Callback? _TWAIN_Callback;

  ffi.Pointer<ffi.Void> DSM_MemAllocate(
    int arg0,
  ) {
    return (_DSM_MemAllocate ??=
        _dylib.lookupFunction<_c_DSM_MemAllocate, _dart_DSM_MemAllocate>(
            'DSM_MemAllocate'))(
      arg0,
    );
  }

  _dart_DSM_MemAllocate? _DSM_MemAllocate;

  void DSM_MemFree(
    ffi.Pointer<ffi.Void> arg0,
  ) {
    return (_DSM_MemFree ??= _dylib
        .lookupFunction<_c_DSM_MemFree, _dart_DSM_MemFree>('DSM_MemFree'))(
      arg0,
    );
  }

  _dart_DSM_MemFree? _DSM_MemFree;

  ffi.Pointer<ffi.Void> DSM_MemLock(
    ffi.Pointer<ffi.Void> arg0,
  ) {
    return (_DSM_MemLock ??= _dylib
        .lookupFunction<_c_DSM_MemLock, _dart_DSM_MemLock>('DSM_MemLock'))(
      arg0,
    );
  }

  _dart_DSM_MemLock? _DSM_MemLock;

  void DSM_MemUnlock(
    ffi.Pointer<ffi.Void> arg0,
  ) {
    return (_DSM_MemUnlock ??=
        _dylib.lookupFunction<_c_DSM_MemUnlock, _dart_DSM_MemUnlock>(
            'DSM_MemUnlock'))(
      arg0,
    );
  }

  _dart_DSM_MemUnlock? _DSM_MemUnlock;
}

/// Structure Definitions                                                    *
class TW_FIX32 extends ffi.Struct {
  @ffi.Int16()
  external int Whole;

  @ffi.Uint16()
  external int Frac;
}

class TW_FRAME extends ffi.Struct {
  external TW_FIX32 Left;

  external TW_FIX32 Top;

  external TW_FIX32 Right;

  external TW_FIX32 Bottom;
}

class TW_DECODEFUNCTION extends ffi.Struct {
  external TW_FIX32 StartIn;

  external TW_FIX32 BreakIn;

  external TW_FIX32 EndIn;

  external TW_FIX32 StartOut;

  external TW_FIX32 BreakOut;

  external TW_FIX32 EndOut;

  external TW_FIX32 Gamma;

  external TW_FIX32 SampleCount;
}

class TW_TRANSFORMSTAGE extends ffi.Opaque {}

class TW_ARRAY extends ffi.Opaque {}

class TW_AUDIOINFO extends ffi.Opaque {}

class TW_CALLBACK extends ffi.Struct {
  external ffi.Pointer<ffi.Void> CallBackProc;

  @ffi.Uint32()
  external int RefCon;

  @ffi.Int16()
  external int Message;
}

class TW_CALLBACK2 extends ffi.Struct {
  external ffi.Pointer<ffi.Void> CallBackProc;

  @ffi.Uint64()
  external int RefCon;

  @ffi.Int16()
  external int Message;
}

class TW_CAPABILITY extends ffi.Struct {
  @ffi.Uint16()
  external int Cap;

  @ffi.Uint16()
  external int ConType;

  external ffi.Pointer<ffi.Void> hContainer;
}

class TW_CIEPOINT extends ffi.Struct {
  external TW_FIX32 X;

  external TW_FIX32 Y;

  external TW_FIX32 Z;
}

class TW_CIECOLOR extends ffi.Opaque {}

class TW_CUSTOMDSDATA extends ffi.Struct {
  @ffi.Uint32()
  external int InfoLength;

  external ffi.Pointer<ffi.Void> hData;
}

class TW_DEVICEEVENT extends ffi.Opaque {}

class TW_ELEMENT8 extends ffi.Struct {
  @ffi.Uint8()
  external int Index;

  @ffi.Uint8()
  external int Channel1;

  @ffi.Uint8()
  external int Channel2;

  @ffi.Uint8()
  external int Channel3;
}

class TW_ENUMERATION extends ffi.Opaque {}

class TW_EVENT extends ffi.Struct {
  external ffi.Pointer<ffi.Void> pEvent;

  @ffi.Uint16()
  external int TWMessage;
}

class TW_INFO extends ffi.Struct {
  @ffi.Uint16()
  external int InfoID;

  @ffi.Uint16()
  external int ItemType;

  @ffi.Uint16()
  external int NumItems;

  @ffi.Uint64()
  external int Item;
}

class TW_EXTIMAGEINFO extends ffi.Opaque {}

class TW_FILESYSTEM extends ffi.Opaque {}

class TW_GRAYRESPONSE extends ffi.Opaque {}

class TW_VERSION extends ffi.Struct {
  @ffi.Uint16()
  external int MajorNum;

  @ffi.Uint16()
  external int MinorNum;

  @ffi.Uint16()
  external int Language;

  @ffi.Uint16()
  external int Country;
  
  @ffi.Array(34)
  external ffi.Array<ffi.Int8> Info;
}

class TW_IDENTITY extends ffi.Opaque {}

class TW_IMAGEINFO extends ffi.Opaque {}

class TW_IMAGELAYOUT extends ffi.Struct {
  external TW_FRAME Frame;

  @ffi.Uint32()
  external int DocumentNumber;

  @ffi.Uint32()
  external int PageNumber;

  @ffi.Uint32()
  external int FrameNumber;
}

class TW_MEMORY extends ffi.Struct {
  @ffi.Uint32()
  external int Flags;

  @ffi.Uint32()
  external int Length;

  external ffi.Pointer<ffi.Void> TheMem;
}

class TW_IMAGEMEMXFER extends ffi.Struct {
  @ffi.Uint16()
  external int Compression;

  @ffi.Uint32()
  external int BytesPerRow;

  @ffi.Uint32()
  external int Columns;

  @ffi.Uint32()
  external int Rows;

  @ffi.Uint32()
  external int XOffset;

  @ffi.Uint32()
  external int YOffset;

  @ffi.Uint32()
  external int BytesWritten;

  external TW_MEMORY Memory;
}

class TW_JPEGCOMPRESSION extends ffi.Opaque {}

class TW_METRICS extends ffi.Struct {
  @ffi.Uint32()
  external int SizeOf;

  @ffi.Uint32()
  external int ImageCount;

  @ffi.Uint32()
  external int SheetCount;
}

class TW_ONEVALUE extends ffi.Struct {
  @ffi.Uint16()
  external int ItemType;

  @ffi.Uint32()
  external int Item;
}

class TW_PALETTE8 extends ffi.Opaque {}

class TW_PASSTHRU extends ffi.Struct {
  external ffi.Pointer<ffi.Void> pCommand;

  @ffi.Uint32()
  external int CommandBytes;

  @ffi.Int32()
  external int Direction;

  external ffi.Pointer<ffi.Void> pData;

  @ffi.Uint32()
  external int DataBytes;

  @ffi.Uint32()
  external int DataBytesXfered;
}

class TW_PENDINGXFERS extends ffi.Struct {
  @ffi.Uint16()
  external int Count;
}

class TW_RANGE extends ffi.Struct {
  @ffi.Uint16()
  external int ItemType;

  @ffi.Uint32()
  external int MinValue;

  @ffi.Uint32()
  external int MaxValue;

  @ffi.Uint32()
  external int StepSize;

  @ffi.Uint32()
  external int DefaultValue;

  @ffi.Uint32()
  external int CurrentValue;
}

class TW_RGBRESPONSE extends ffi.Opaque {}

class TW_SETUPFILEXFER extends ffi.Opaque {}

class TW_SETUPMEMXFER extends ffi.Struct {
  @ffi.Uint32()
  external int MinBufSize;

  @ffi.Uint32()
  external int MaxBufSize;

  @ffi.Uint32()
  external int Preferred;
}

class TW_STATUS extends ffi.Struct {
  @ffi.Uint16()
  external int ConditionCode;
}

class TW_STATUSUTF8 extends ffi.Struct {
  external TW_STATUS Status;

  @ffi.Uint32()
  external int Size;

  external ffi.Pointer<ffi.Void> UTF8string;
}

class TW_TWAINDIRECT extends ffi.Struct {
  @ffi.Uint32()
  external int SizeOf;

  @ffi.Uint16()
  external int CommunicationManager;

  external ffi.Pointer<ffi.Void> Send;

  @ffi.Uint32()
  external int SendSize;

  external ffi.Pointer<ffi.Void> Receive;

  @ffi.Uint32()
  external int ReceiveSize;
}

class TW_USERINTERFACE extends ffi.Struct {
  @ffi.Uint16()
  external int ShowUI;

  @ffi.Uint16()
  external int ModalUI;

  external ffi.Pointer<ffi.Void> hParent;
}

class TW_SETUPFILEXFER2 extends ffi.Struct {
  external ffi.Pointer<ffi.Void> FileName;

  @ffi.Uint16()
  external int FileNameType;

  @ffi.Uint16()
  external int Format;

  @ffi.Int16()
  external int VRefNum;

  @ffi.Uint32()
  external int parID;
}

class TW_TWUNKIDENTITY extends ffi.Opaque {}

class TW_TWUNKDSENTRYPARAMS extends ffi.Opaque {}

class TW_TWUNKDSENTRYRETURN extends ffi.Struct {
  @ffi.Uint16()
  external int returnCode;

  @ffi.Uint16()
  external int conditionCode;

  @ffi.Int32()
  external int pDataSize;
}

class TW_CAPEXT extends ffi.Struct {
  @ffi.Uint16()
  external int Cap;

  @ffi.Uint16()
  external int Properties;
}

class TW_SETUPAUDIOFILEXFER extends ffi.Opaque {}

class TW_ENTRYPOINT extends ffi.Struct {
  @ffi.Uint32()
  external int Size;

  external ffi.Pointer<ffi.NativeFunction<DSMENTRYPROC>> DSM_Entry;

  external ffi.Pointer<ffi.NativeFunction<DSM_MEMALLOCATE>> DSM_MemAllocate;

  external ffi.Pointer<ffi.NativeFunction<DSM_MEMFREE>> DSM_MemFree;

  external ffi.Pointer<ffi.NativeFunction<DSM_MEMLOCK>> DSM_MemLock;

  external ffi.Pointer<ffi.NativeFunction<DSM_MEMUNLOCK>> DSM_MemUnlock;
}

class TW_FILTER_DESCRIPTOR extends ffi.Struct {
  @ffi.Uint32()
  external int Size;

  @ffi.Uint32()
  external int HueStart;

  @ffi.Uint32()
  external int HueEnd;

  @ffi.Uint32()
  external int SaturationStart;

  @ffi.Uint32()
  external int SaturationEnd;

  @ffi.Uint32()
  external int ValueStart;

  @ffi.Uint32()
  external int ValueEnd;

  @ffi.Uint32()
  external int Replacement;
}

class TW_FILTER extends ffi.Struct {
  @ffi.Uint32()
  external int Size;

  @ffi.Uint32()
  external int DescriptorCount;

  @ffi.Uint32()
  external int MaxDescriptorCount;

  @ffi.Uint32()
  external int Condition;

  external ffi.Pointer<ffi.Void> hDescriptors;
}

const int TWON_PROTOCOLMINOR = 4;

const int TWON_PROTOCOLMAJOR = 2;

const int TWON_ARRAY = 3;

const int TWON_ENUMERATION = 4;

const int TWON_ONEVALUE = 5;

const int TWON_RANGE = 6;

const int TWON_ICONID = 962;

const int TWON_DSMID = 461;

const int TWON_DSMCODEID = 63;

const int TWON_DONTCARE8 = 255;

const int TWON_DONTCARE16 = 65535;

const int TWON_DONTCARE32 = 4294967295;

const int TWMF_APPOWNS = 1;

const int TWMF_DSMOWNS = 2;

const int TWMF_DSOWNS = 4;

const int TWMF_POINTER = 8;

const int TWMF_HANDLE = 16;

const int TWTY_INT8 = 0;

const int TWTY_INT16 = 1;

const int TWTY_INT32 = 2;

const int TWTY_UINT8 = 3;

const int TWTY_UINT16 = 4;

const int TWTY_UINT32 = 5;

const int TWTY_BOOL = 6;

const int TWTY_FIX32 = 7;

const int TWTY_FRAME = 8;

const int TWTY_STR32 = 9;

const int TWTY_STR64 = 10;

const int TWTY_STR128 = 11;

const int TWTY_STR255 = 12;

const int TWTY_HANDLE = 15;

const int TWAL_ALARM = 0;

const int TWAL_FEEDERERROR = 1;

const int TWAL_FEEDERWARNING = 2;

const int TWAL_BARCODE = 3;

const int TWAL_DOUBLEFEED = 4;

const int TWAL_JAM = 5;

const int TWAL_PATCHCODE = 6;

const int TWAL_POWER = 7;

const int TWAL_SKEW = 8;

const int TWAS_NONE = 0;

const int TWAS_AUTO = 1;

const int TWAS_CURRENT = 2;

const int TWBCOR_ROT0 = 0;

const int TWBCOR_ROT90 = 1;

const int TWBCOR_ROT180 = 2;

const int TWBCOR_ROT270 = 3;

const int TWBCOR_ROTX = 4;

const int TWBD_HORZ = 0;

const int TWBD_VERT = 1;

const int TWBD_HORZVERT = 2;

const int TWBD_VERTHORZ = 3;

const int TWBO_LSBFIRST = 0;

const int TWBO_MSBFIRST = 1;

const int TWBP_DISABLE = -2;

const int TWBP_AUTO = -1;

const int TWBR_THRESHOLD = 0;

const int TWBR_HALFTONE = 1;

const int TWBR_CUSTHALFTONE = 2;

const int TWBR_DIFFUSION = 3;

const int TWBR_DYNAMICTHRESHOLD = 4;

const int TWBT_3OF9 = 0;

const int TWBT_2OF5INTERLEAVED = 1;

const int TWBT_2OF5NONINTERLEAVED = 2;

const int TWBT_CODE93 = 3;

const int TWBT_CODE128 = 4;

const int TWBT_UCC128 = 5;

const int TWBT_CODABAR = 6;

const int TWBT_UPCA = 7;

const int TWBT_UPCE = 8;

const int TWBT_EAN8 = 9;

const int TWBT_EAN13 = 10;

const int TWBT_POSTNET = 11;

const int TWBT_PDF417 = 12;

const int TWBT_2OF5INDUSTRIAL = 13;

const int TWBT_2OF5MATRIX = 14;

const int TWBT_2OF5DATALOGIC = 15;

const int TWBT_2OF5IATA = 16;

const int TWBT_3OF9FULLASCII = 17;

const int TWBT_CODABARWITHSTARTSTOP = 18;

const int TWBT_MAXICODE = 19;

const int TWBT_QRCODE = 20;

const int TWCP_NONE = 0;

const int TWCP_PACKBITS = 1;

const int TWCP_GROUP31D = 2;

const int TWCP_GROUP31DEOL = 3;

const int TWCP_GROUP32D = 4;

const int TWCP_GROUP4 = 5;

const int TWCP_JPEG = 6;

const int TWCP_LZW = 7;

const int TWCP_JBIG = 8;

const int TWCP_PNG = 9;

const int TWCP_RLE4 = 10;

const int TWCP_RLE8 = 11;

const int TWCP_BITFIELDS = 12;

const int TWCP_ZIP = 13;

const int TWCP_JPEG2000 = 14;

const int TWCS_BOTH = 0;

const int TWCS_TOP = 1;

const int TWCS_BOTTOM = 2;

const int TWDE_CUSTOMEVENTS = 32768;

const int TWDE_CHECKAUTOMATICCAPTURE = 0;

const int TWDE_CHECKBATTERY = 1;

const int TWDE_CHECKDEVICEONLINE = 2;

const int TWDE_CHECKFLASH = 3;

const int TWDE_CHECKPOWERSUPPLY = 4;

const int TWDE_CHECKRESOLUTION = 5;

const int TWDE_DEVICEADDED = 6;

const int TWDE_DEVICEOFFLINE = 7;

const int TWDE_DEVICEREADY = 8;

const int TWDE_DEVICEREMOVED = 9;

const int TWDE_IMAGECAPTURED = 10;

const int TWDE_IMAGEDELETED = 11;

const int TWDE_PAPERDOUBLEFEED = 12;

const int TWDE_PAPERJAM = 13;

const int TWDE_LAMPFAILURE = 14;

const int TWDE_POWERSAVE = 15;

const int TWDE_POWERSAVENOTIFY = 16;

const int TWDR_GET = 1;

const int TWDR_SET = 2;

const int TWDSK_SUCCESS = 0;

const int TWDSK_REPORTONLY = 1;

const int TWDSK_FAIL = 2;

const int TWDSK_DISABLED = 3;

const int TWDX_NONE = 0;

const int TWDX_1PASSDUPLEX = 1;

const int TWDX_2PASSDUPLEX = 2;

const int TWFA_NONE = 0;

const int TWFA_LEFT = 1;

const int TWFA_CENTER = 2;

const int TWFA_RIGHT = 3;

const int TWFE_GENERAL = 0;

const int TWFE_PHOTO = 1;

const int TWFF_TIFF = 0;

const int TWFF_PICT = 1;

const int TWFF_BMP = 2;

const int TWFF_XBM = 3;

const int TWFF_JFIF = 4;

const int TWFF_FPX = 5;

const int TWFF_TIFFMULTI = 6;

const int TWFF_PNG = 7;

const int TWFF_SPIFF = 8;

const int TWFF_EXIF = 9;

const int TWFF_PDF = 10;

const int TWFF_JP2 = 11;

const int TWFF_JPX = 13;

const int TWFF_DEJAVU = 14;

const int TWFF_PDFA = 15;

const int TWFF_PDFA2 = 16;

const int TWFF_PDFRASTER = 17;

const int TWFL_NONE = 0;

const int TWFL_OFF = 1;

const int TWFL_ON = 2;

const int TWFL_AUTO = 3;

const int TWFL_REDEYE = 4;

const int TWFO_FIRSTPAGEFIRST = 0;

const int TWFO_LASTPAGEFIRST = 1;

const int TWFP_POCKETERROR = 0;

const int TWFP_POCKET1 = 1;

const int TWFP_POCKET2 = 2;

const int TWFP_POCKET3 = 3;

const int TWFP_POCKET4 = 4;

const int TWFP_POCKET5 = 5;

const int TWFP_POCKET6 = 6;

const int TWFP_POCKET7 = 7;

const int TWFP_POCKET8 = 8;

const int TWFP_POCKET9 = 9;

const int TWFP_POCKET10 = 10;

const int TWFP_POCKET11 = 11;

const int TWFP_POCKET12 = 12;

const int TWFP_POCKET13 = 13;

const int TWFP_POCKET14 = 14;

const int TWFP_POCKET15 = 15;

const int TWFP_POCKET16 = 16;

const int TWFR_BOOK = 0;

const int TWFR_FANFOLD = 1;

const int TWFT_RED = 0;

const int TWFT_GREEN = 1;

const int TWFT_BLUE = 2;

const int TWFT_NONE = 3;

const int TWFT_WHITE = 4;

const int TWFT_CYAN = 5;

const int TWFT_MAGENTA = 6;

const int TWFT_YELLOW = 7;

const int TWFT_BLACK = 8;

const int TWFY_CAMERA = 0;

const int TWFY_CAMERATOP = 1;

const int TWFY_CAMERABOTTOM = 2;

const int TWFY_CAMERAPREVIEW = 3;

const int TWFY_DOMAIN = 4;

const int TWFY_HOST = 5;

const int TWFY_DIRECTORY = 6;

const int TWFY_IMAGE = 7;

const int TWFY_UNKNOWN = 8;

const int TWIC_NONE = 0;

const int TWIC_LINK = 1;

const int TWIC_EMBED = 2;

const int TWIF_NONE = 0;

const int TWIF_AUTO = 1;

const int TWIF_LOWPASS = 2;

const int TWIF_BANDPASS = 3;

const int TWIF_HIGHPASS = 4;

const int TWIF_TEXT = 3;

const int TWIF_FINELINE = 4;

const int TWIM_NONE = 0;

const int TWIM_FRONTONTOP = 1;

const int TWIM_FRONTONBOTTOM = 2;

const int TWIM_FRONTONLEFT = 3;

const int TWIM_FRONTONRIGHT = 4;

const int TWJC_NONE = 0;

const int TWJC_JSIC = 1;

const int TWJC_JSIS = 2;

const int TWJC_JSXC = 3;

const int TWJC_JSXS = 4;

const int TWJQ_UNKNOWN = -4;

const int TWJQ_LOW = -3;

const int TWJQ_MEDIUM = -2;

const int TWJQ_HIGH = -1;

const int TWLP_REFLECTIVE = 0;

const int TWLP_TRANSMISSIVE = 1;

const int TWLS_RED = 0;

const int TWLS_GREEN = 1;

const int TWLS_BLUE = 2;

const int TWLS_NONE = 3;

const int TWLS_WHITE = 4;

const int TWLS_UV = 5;

const int TWLS_IR = 6;

const int TWMD_MICR = 0;

const int TWMD_RAW = 1;

const int TWMD_INVALID = 2;

const int TWNF_NONE = 0;

const int TWNF_AUTO = 1;

const int TWNF_LONEPIXEL = 2;

const int TWNF_MAJORITYRULE = 3;

const int TWOR_ROT0 = 0;

const int TWOR_ROT90 = 1;

const int TWOR_ROT180 = 2;

const int TWOR_ROT270 = 3;

const int TWOR_PORTRAIT = 0;

const int TWOR_LANDSCAPE = 3;

const int TWOR_AUTO = 4;

const int TWOR_AUTOTEXT = 5;

const int TWOR_AUTOPICTURE = 6;

const int TWOV_NONE = 0;

const int TWOV_AUTO = 1;

const int TWOV_TOPBOTTOM = 2;

const int TWOV_LEFTRIGHT = 3;

const int TWOV_ALL = 4;

const int TWPA_RGB = 0;

const int TWPA_GRAY = 1;

const int TWPA_CMY = 2;

const int TWPC_CHUNKY = 0;

const int TWPC_PLANAR = 1;

const int TWPCH_PATCH1 = 0;

const int TWPCH_PATCH2 = 1;

const int TWPCH_PATCH3 = 2;

const int TWPCH_PATCH4 = 3;

const int TWPCH_PATCH6 = 4;

const int TWPCH_PATCHT = 5;

const int TWPF_CHOCOLATE = 0;

const int TWPF_VANILLA = 1;

const int TWPM_SINGLESTRING = 0;

const int TWPM_MULTISTRING = 1;

const int TWPM_COMPOUNDSTRING = 2;

const int TWPR_IMPRINTERTOPBEFORE = 0;

const int TWPR_IMPRINTERTOPAFTER = 1;

const int TWPR_IMPRINTERBOTTOMBEFORE = 2;

const int TWPR_IMPRINTERBOTTOMAFTER = 3;

const int TWPR_ENDORSERTOPBEFORE = 4;

const int TWPR_ENDORSERTOPAFTER = 5;

const int TWPR_ENDORSERBOTTOMBEFORE = 6;

const int TWPR_ENDORSERBOTTOMAFTER = 7;

const int TWPF_NORMAL = 0;

const int TWPF_BOLD = 1;

const int TWPF_ITALIC = 2;

const int TWPF_LARGESIZE = 3;

const int TWPF_SMALLSIZE = 4;

const int TWCT_PAGE = 0;

const int TWCT_PATCH1 = 1;

const int TWCT_PATCH2 = 2;

const int TWCT_PATCH3 = 3;

const int TWCT_PATCH4 = 4;

const int TWCT_PATCHT = 5;

const int TWCT_PATCH6 = 6;

const int TWPS_EXTERNAL = 0;

const int TWPS_BATTERY = 1;

const int TWPT_BW = 0;

const int TWPT_GRAY = 1;

const int TWPT_RGB = 2;

const int TWPT_PALETTE = 3;

const int TWPT_CMY = 4;

const int TWPT_CMYK = 5;

const int TWPT_YUV = 6;

const int TWPT_YUVK = 7;

const int TWPT_CIEXYZ = 8;

const int TWPT_LAB = 9;

const int TWPT_SRGB = 10;

const int TWPT_SCRGB = 11;

const int TWPT_INFRARED = 16;

const int TWSG_NONE = 0;

const int TWSG_AUTO = 1;

const int TWSG_MANUAL = 2;

const int TWFM_POSITIVE = 0;

const int TWFM_NEGATIVE = 1;

const int TWDF_ULTRASONIC = 0;

const int TWDF_BYLENGTH = 1;

const int TWDF_INFRARED = 2;

const int TWUS_LOW = 0;

const int TWUS_MEDIUM = 1;

const int TWUS_HIGH = 2;

const int TWDP_STOP = 0;

const int TWDP_STOPANDWAIT = 1;

const int TWDP_SOUND = 2;

const int TWDP_DONOTIMPRINT = 3;

const int TWMR_NONE = 0;

const int TWMR_VERTICAL = 1;

const int TWMR_HORIZONTAL = 2;

const int TWJS_444YCBCR = 0;

const int TWJS_444RGB = 1;

const int TWJS_422 = 2;

const int TWJS_421 = 3;

const int TWJS_411 = 4;

const int TWJS_420 = 5;

const int TWJS_410 = 6;

const int TWJS_311 = 7;

const int TWPH_NORMAL = 0;

const int TWPH_FRAGILE = 1;

const int TWPH_THICK = 2;

const int TWPH_TRIFOLD = 3;

const int TWPH_PHOTOGRAPH = 4;

const int TWCI_INFO = 0;

const int TWCI_WARNING = 1;

const int TWCI_ERROR = 2;

const int TWCI_WARMUP = 3;

const int TWSS_NONE = 0;

const int TWSS_A4 = 1;

const int TWSS_JISB5 = 2;

const int TWSS_USLETTER = 3;

const int TWSS_USLEGAL = 4;

const int TWSS_A5 = 5;

const int TWSS_ISOB4 = 6;

const int TWSS_ISOB6 = 7;

const int TWSS_USLEDGER = 9;

const int TWSS_USEXECUTIVE = 10;

const int TWSS_A3 = 11;

const int TWSS_ISOB3 = 12;

const int TWSS_A6 = 13;

const int TWSS_C4 = 14;

const int TWSS_C5 = 15;

const int TWSS_C6 = 16;

const int TWSS_4A0 = 17;

const int TWSS_2A0 = 18;

const int TWSS_A0 = 19;

const int TWSS_A1 = 20;

const int TWSS_A2 = 21;

const int TWSS_A7 = 22;

const int TWSS_A8 = 23;

const int TWSS_A9 = 24;

const int TWSS_A10 = 25;

const int TWSS_ISOB0 = 26;

const int TWSS_ISOB1 = 27;

const int TWSS_ISOB2 = 28;

const int TWSS_ISOB5 = 29;

const int TWSS_ISOB7 = 30;

const int TWSS_ISOB8 = 31;

const int TWSS_ISOB9 = 32;

const int TWSS_ISOB10 = 33;

const int TWSS_JISB0 = 34;

const int TWSS_JISB1 = 35;

const int TWSS_JISB2 = 36;

const int TWSS_JISB3 = 37;

const int TWSS_JISB4 = 38;

const int TWSS_JISB6 = 39;

const int TWSS_JISB7 = 40;

const int TWSS_JISB8 = 41;

const int TWSS_JISB9 = 42;

const int TWSS_JISB10 = 43;

const int TWSS_C0 = 44;

const int TWSS_C1 = 45;

const int TWSS_C2 = 46;

const int TWSS_C3 = 47;

const int TWSS_C7 = 48;

const int TWSS_C8 = 49;

const int TWSS_C9 = 50;

const int TWSS_C10 = 51;

const int TWSS_USSTATEMENT = 52;

const int TWSS_BUSINESSCARD = 53;

const int TWSS_MAXSIZE = 54;

const int TWSX_NATIVE = 0;

const int TWSX_FILE = 1;

const int TWSX_MEMORY = 2;

const int TWSX_MEMFILE = 4;

const int TWUN_INCHES = 0;

const int TWUN_CENTIMETERS = 1;

const int TWUN_PICAS = 2;

const int TWUN_POINTS = 3;

const int TWUN_TWIPS = 4;

const int TWUN_PIXELS = 5;

const int TWUN_MILLIMETERS = 6;

const int TWCY_AFGHANISTAN = 1001;

const int TWCY_ALGERIA = 213;

const int TWCY_AMERICANSAMOA = 684;

const int TWCY_ANDORRA = 33;

const int TWCY_ANGOLA = 1002;

const int TWCY_ANGUILLA = 8090;

const int TWCY_ANTIGUA = 8091;

const int TWCY_ARGENTINA = 54;

const int TWCY_ARUBA = 297;

const int TWCY_ASCENSIONI = 247;

const int TWCY_AUSTRALIA = 61;

const int TWCY_AUSTRIA = 43;

const int TWCY_BAHAMAS = 8092;

const int TWCY_BAHRAIN = 973;

const int TWCY_BANGLADESH = 880;

const int TWCY_BARBADOS = 8093;

const int TWCY_BELGIUM = 32;

const int TWCY_BELIZE = 501;

const int TWCY_BENIN = 229;

const int TWCY_BERMUDA = 8094;

const int TWCY_BHUTAN = 1003;

const int TWCY_BOLIVIA = 591;

const int TWCY_BOTSWANA = 267;

const int TWCY_BRITAIN = 6;

const int TWCY_BRITVIRGINIS = 8095;

const int TWCY_BRAZIL = 55;

const int TWCY_BRUNEI = 673;

const int TWCY_BULGARIA = 359;

const int TWCY_BURKINAFASO = 1004;

const int TWCY_BURMA = 1005;

const int TWCY_BURUNDI = 1006;

const int TWCY_CAMAROON = 237;

const int TWCY_CANADA = 2;

const int TWCY_CAPEVERDEIS = 238;

const int TWCY_CAYMANIS = 8096;

const int TWCY_CENTRALAFREP = 1007;

const int TWCY_CHAD = 1008;

const int TWCY_CHILE = 56;

const int TWCY_CHINA = 86;

const int TWCY_CHRISTMASIS = 1009;

const int TWCY_COCOSIS = 1009;

const int TWCY_COLOMBIA = 57;

const int TWCY_COMOROS = 1010;

const int TWCY_CONGO = 1011;

const int TWCY_COOKIS = 1012;

const int TWCY_COSTARICA = 506;

const int TWCY_CUBA = 5;

const int TWCY_CYPRUS = 357;

const int TWCY_CZECHOSLOVAKIA = 42;

const int TWCY_DENMARK = 45;

const int TWCY_DJIBOUTI = 1013;

const int TWCY_DOMINICA = 8097;

const int TWCY_DOMINCANREP = 8098;

const int TWCY_EASTERIS = 1014;

const int TWCY_ECUADOR = 593;

const int TWCY_EGYPT = 20;

const int TWCY_ELSALVADOR = 503;

const int TWCY_EQGUINEA = 1015;

const int TWCY_ETHIOPIA = 251;

const int TWCY_FALKLANDIS = 1016;

const int TWCY_FAEROEIS = 298;

const int TWCY_FIJIISLANDS = 679;

const int TWCY_FINLAND = 358;

const int TWCY_FRANCE = 33;

const int TWCY_FRANTILLES = 596;

const int TWCY_FRGUIANA = 594;

const int TWCY_FRPOLYNEISA = 689;

const int TWCY_FUTANAIS = 1043;

const int TWCY_GABON = 241;

const int TWCY_GAMBIA = 220;

const int TWCY_GERMANY = 49;

const int TWCY_GHANA = 233;

const int TWCY_GIBRALTER = 350;

const int TWCY_GREECE = 30;

const int TWCY_GREENLAND = 299;

const int TWCY_GRENADA = 8099;

const int TWCY_GRENEDINES = 8015;

const int TWCY_GUADELOUPE = 590;

const int TWCY_GUAM = 671;

const int TWCY_GUANTANAMOBAY = 5399;

const int TWCY_GUATEMALA = 502;

const int TWCY_GUINEA = 224;

const int TWCY_GUINEABISSAU = 1017;

const int TWCY_GUYANA = 592;

const int TWCY_HAITI = 509;

const int TWCY_HONDURAS = 504;

const int TWCY_HONGKONG = 852;

const int TWCY_HUNGARY = 36;

const int TWCY_ICELAND = 354;

const int TWCY_INDIA = 91;

const int TWCY_INDONESIA = 62;

const int TWCY_IRAN = 98;

const int TWCY_IRAQ = 964;

const int TWCY_IRELAND = 353;

const int TWCY_ISRAEL = 972;

const int TWCY_ITALY = 39;

const int TWCY_IVORYCOAST = 225;

const int TWCY_JAMAICA = 8010;

const int TWCY_JAPAN = 81;

const int TWCY_JORDAN = 962;

const int TWCY_KENYA = 254;

const int TWCY_KIRIBATI = 1018;

const int TWCY_KOREA = 82;

const int TWCY_KUWAIT = 965;

const int TWCY_LAOS = 1019;

const int TWCY_LEBANON = 1020;

const int TWCY_LIBERIA = 231;

const int TWCY_LIBYA = 218;

const int TWCY_LIECHTENSTEIN = 41;

const int TWCY_LUXENBOURG = 352;

const int TWCY_MACAO = 853;

const int TWCY_MADAGASCAR = 1021;

const int TWCY_MALAWI = 265;

const int TWCY_MALAYSIA = 60;

const int TWCY_MALDIVES = 960;

const int TWCY_MALI = 1022;

const int TWCY_MALTA = 356;

const int TWCY_MARSHALLIS = 692;

const int TWCY_MAURITANIA = 1023;

const int TWCY_MAURITIUS = 230;

const int TWCY_MEXICO = 3;

const int TWCY_MICRONESIA = 691;

const int TWCY_MIQUELON = 508;

const int TWCY_MONACO = 33;

const int TWCY_MONGOLIA = 1024;

const int TWCY_MONTSERRAT = 8011;

const int TWCY_MOROCCO = 212;

const int TWCY_MOZAMBIQUE = 1025;

const int TWCY_NAMIBIA = 264;

const int TWCY_NAURU = 1026;

const int TWCY_NEPAL = 977;

const int TWCY_NETHERLANDS = 31;

const int TWCY_NETHANTILLES = 599;

const int TWCY_NEVIS = 8012;

const int TWCY_NEWCALEDONIA = 687;

const int TWCY_NEWZEALAND = 64;

const int TWCY_NICARAGUA = 505;

const int TWCY_NIGER = 227;

const int TWCY_NIGERIA = 234;

const int TWCY_NIUE = 1027;

const int TWCY_NORFOLKI = 1028;

const int TWCY_NORWAY = 47;

const int TWCY_OMAN = 968;

const int TWCY_PAKISTAN = 92;

const int TWCY_PALAU = 1029;

const int TWCY_PANAMA = 507;

const int TWCY_PARAGUAY = 595;

const int TWCY_PERU = 51;

const int TWCY_PHILLIPPINES = 63;

const int TWCY_PITCAIRNIS = 1030;

const int TWCY_PNEWGUINEA = 675;

const int TWCY_POLAND = 48;

const int TWCY_PORTUGAL = 351;

const int TWCY_QATAR = 974;

const int TWCY_REUNIONI = 1031;

const int TWCY_ROMANIA = 40;

const int TWCY_RWANDA = 250;

const int TWCY_SAIPAN = 670;

const int TWCY_SANMARINO = 39;

const int TWCY_SAOTOME = 1033;

const int TWCY_SAUDIARABIA = 966;

const int TWCY_SENEGAL = 221;

const int TWCY_SEYCHELLESIS = 1034;

const int TWCY_SIERRALEONE = 1035;

const int TWCY_SINGAPORE = 65;

const int TWCY_SOLOMONIS = 1036;

const int TWCY_SOMALI = 1037;

const int TWCY_SOUTHAFRICA = 27;

const int TWCY_SPAIN = 34;

const int TWCY_SRILANKA = 94;

const int TWCY_STHELENA = 1032;

const int TWCY_STKITTS = 8013;

const int TWCY_STLUCIA = 8014;

const int TWCY_STPIERRE = 508;

const int TWCY_STVINCENT = 8015;

const int TWCY_SUDAN = 1038;

const int TWCY_SURINAME = 597;

const int TWCY_SWAZILAND = 268;

const int TWCY_SWEDEN = 46;

const int TWCY_SWITZERLAND = 41;

const int TWCY_SYRIA = 1039;

const int TWCY_TAIWAN = 886;

const int TWCY_TANZANIA = 255;

const int TWCY_THAILAND = 66;

const int TWCY_TOBAGO = 8016;

const int TWCY_TOGO = 228;

const int TWCY_TONGAIS = 676;

const int TWCY_TRINIDAD = 8016;

const int TWCY_TUNISIA = 216;

const int TWCY_TURKEY = 90;

const int TWCY_TURKSCAICOS = 8017;

const int TWCY_TUVALU = 1040;

const int TWCY_UGANDA = 256;

const int TWCY_USSR = 7;

const int TWCY_UAEMIRATES = 971;

const int TWCY_UNITEDKINGDOM = 44;

const int TWCY_USA = 1;

const int TWCY_URUGUAY = 598;

const int TWCY_VANUATU = 1041;

const int TWCY_VATICANCITY = 39;

const int TWCY_VENEZUELA = 58;

const int TWCY_WAKE = 1042;

const int TWCY_WALLISIS = 1043;

const int TWCY_WESTERNSAHARA = 1044;

const int TWCY_WESTERNSAMOA = 1045;

const int TWCY_YEMEN = 1046;

const int TWCY_YUGOSLAVIA = 38;

const int TWCY_ZAIRE = 243;

const int TWCY_ZAMBIA = 260;

const int TWCY_ZIMBABWE = 263;

const int TWCY_ALBANIA = 355;

const int TWCY_ARMENIA = 374;

const int TWCY_AZERBAIJAN = 994;

const int TWCY_BELARUS = 375;

const int TWCY_BOSNIAHERZGO = 387;

const int TWCY_CAMBODIA = 855;

const int TWCY_CROATIA = 385;

const int TWCY_CZECHREPUBLIC = 420;

const int TWCY_DIEGOGARCIA = 246;

const int TWCY_ERITREA = 291;

const int TWCY_ESTONIA = 372;

const int TWCY_GEORGIA = 995;

const int TWCY_LATVIA = 371;

const int TWCY_LESOTHO = 266;

const int TWCY_LITHUANIA = 370;

const int TWCY_MACEDONIA = 389;

const int TWCY_MAYOTTEIS = 269;

const int TWCY_MOLDOVA = 373;

const int TWCY_MYANMAR = 95;

const int TWCY_NORTHKOREA = 850;

const int TWCY_PUERTORICO = 787;

const int TWCY_RUSSIA = 7;

const int TWCY_SERBIA = 381;

const int TWCY_SLOVAKIA = 421;

const int TWCY_SLOVENIA = 386;

const int TWCY_SOUTHKOREA = 82;

const int TWCY_UKRAINE = 380;

const int TWCY_USVIRGINIS = 340;

const int TWCY_VIETNAM = 84;

const int TWLG_USERLOCALE = -1;

const int TWLG_DAN = 0;

const int TWLG_DUT = 1;

const int TWLG_ENG = 2;

const int TWLG_FCF = 3;

const int TWLG_FIN = 4;

const int TWLG_FRN = 5;

const int TWLG_GER = 6;

const int TWLG_ICE = 7;

const int TWLG_ITN = 8;

const int TWLG_NOR = 9;

const int TWLG_POR = 10;

const int TWLG_SPA = 11;

const int TWLG_SWE = 12;

const int TWLG_USA = 13;

const int TWLG_AFRIKAANS = 14;

const int TWLG_ALBANIA = 15;

const int TWLG_ARABIC = 16;

const int TWLG_ARABIC_ALGERIA = 17;

const int TWLG_ARABIC_BAHRAIN = 18;

const int TWLG_ARABIC_EGYPT = 19;

const int TWLG_ARABIC_IRAQ = 20;

const int TWLG_ARABIC_JORDAN = 21;

const int TWLG_ARABIC_KUWAIT = 22;

const int TWLG_ARABIC_LEBANON = 23;

const int TWLG_ARABIC_LIBYA = 24;

const int TWLG_ARABIC_MOROCCO = 25;

const int TWLG_ARABIC_OMAN = 26;

const int TWLG_ARABIC_QATAR = 27;

const int TWLG_ARABIC_SAUDIARABIA = 28;

const int TWLG_ARABIC_SYRIA = 29;

const int TWLG_ARABIC_TUNISIA = 30;

const int TWLG_ARABIC_UAE = 31;

const int TWLG_ARABIC_YEMEN = 32;

const int TWLG_BASQUE = 33;

const int TWLG_BYELORUSSIAN = 34;

const int TWLG_BULGARIAN = 35;

const int TWLG_CATALAN = 36;

const int TWLG_CHINESE = 37;

const int TWLG_CHINESE_HONGKONG = 38;

const int TWLG_CHINESE_PRC = 39;

const int TWLG_CHINESE_SINGAPORE = 40;

const int TWLG_CHINESE_SIMPLIFIED = 41;

const int TWLG_CHINESE_TAIWAN = 42;

const int TWLG_CHINESE_TRADITIONAL = 43;

const int TWLG_CROATIA = 44;

const int TWLG_CZECH = 45;

const int TWLG_DANISH = 0;

const int TWLG_DUTCH = 1;

const int TWLG_DUTCH_BELGIAN = 46;

const int TWLG_ENGLISH = 2;

const int TWLG_ENGLISH_AUSTRALIAN = 47;

const int TWLG_ENGLISH_CANADIAN = 48;

const int TWLG_ENGLISH_IRELAND = 49;

const int TWLG_ENGLISH_NEWZEALAND = 50;

const int TWLG_ENGLISH_SOUTHAFRICA = 51;

const int TWLG_ENGLISH_UK = 52;

const int TWLG_ENGLISH_USA = 13;

const int TWLG_ESTONIAN = 53;

const int TWLG_FAEROESE = 54;

const int TWLG_FARSI = 55;

const int TWLG_FINNISH = 4;

const int TWLG_FRENCH = 5;

const int TWLG_FRENCH_BELGIAN = 56;

const int TWLG_FRENCH_CANADIAN = 3;

const int TWLG_FRENCH_LUXEMBOURG = 57;

const int TWLG_FRENCH_SWISS = 58;

const int TWLG_GERMAN = 6;

const int TWLG_GERMAN_AUSTRIAN = 59;

const int TWLG_GERMAN_LUXEMBOURG = 60;

const int TWLG_GERMAN_LIECHTENSTEIN = 61;

const int TWLG_GERMAN_SWISS = 62;

const int TWLG_GREEK = 63;

const int TWLG_HEBREW = 64;

const int TWLG_HUNGARIAN = 65;

const int TWLG_ICELANDIC = 7;

const int TWLG_INDONESIAN = 66;

const int TWLG_ITALIAN = 8;

const int TWLG_ITALIAN_SWISS = 67;

const int TWLG_JAPANESE = 68;

const int TWLG_KOREAN = 69;

const int TWLG_KOREAN_JOHAB = 70;

const int TWLG_LATVIAN = 71;

const int TWLG_LITHUANIAN = 72;

const int TWLG_NORWEGIAN = 9;

const int TWLG_NORWEGIAN_BOKMAL = 73;

const int TWLG_NORWEGIAN_NYNORSK = 74;

const int TWLG_POLISH = 75;

const int TWLG_PORTUGUESE = 10;

const int TWLG_PORTUGUESE_BRAZIL = 76;

const int TWLG_ROMANIAN = 77;

const int TWLG_RUSSIAN = 78;

const int TWLG_SERBIAN_LATIN = 79;

const int TWLG_SLOVAK = 80;

const int TWLG_SLOVENIAN = 81;

const int TWLG_SPANISH = 11;

const int TWLG_SPANISH_MEXICAN = 82;

const int TWLG_SPANISH_MODERN = 83;

const int TWLG_SWEDISH = 12;

const int TWLG_THAI = 84;

const int TWLG_TURKISH = 85;

const int TWLG_UKRANIAN = 86;

const int TWLG_ASSAMESE = 87;

const int TWLG_BENGALI = 88;

const int TWLG_BIHARI = 89;

const int TWLG_BODO = 90;

const int TWLG_DOGRI = 91;

const int TWLG_GUJARATI = 92;

const int TWLG_HARYANVI = 93;

const int TWLG_HINDI = 94;

const int TWLG_KANNADA = 95;

const int TWLG_KASHMIRI = 96;

const int TWLG_MALAYALAM = 97;

const int TWLG_MARATHI = 98;

const int TWLG_MARWARI = 99;

const int TWLG_MEGHALAYAN = 100;

const int TWLG_MIZO = 101;

const int TWLG_NAGA = 102;

const int TWLG_ORISSI = 103;

const int TWLG_PUNJABI = 104;

const int TWLG_PUSHTU = 105;

const int TWLG_SERBIAN_CYRILLIC = 106;

const int TWLG_SIKKIMI = 107;

const int TWLG_SWEDISH_FINLAND = 108;

const int TWLG_TAMIL = 109;

const int TWLG_TELUGU = 110;

const int TWLG_TRIPURI = 111;

const int TWLG_URDU = 112;

const int TWLG_VIETNAMESE = 113;

const int DG_CONTROL = 1;

const int DG_IMAGE = 2;

const int DG_AUDIO = 4;

const int DF_DSM2 = 268435456;

const int DF_APP2 = 536870912;

const int DF_DS2 = 1073741824;

const int DG_MASK = 65535;

const int DAT_NULL = 0;

const int DAT_CUSTOMBASE = 32768;

const int DAT_CAPABILITY = 1;

const int DAT_EVENT = 2;

const int DAT_IDENTITY = 3;

const int DAT_PARENT = 4;

const int DAT_PENDINGXFERS = 5;

const int DAT_SETUPMEMXFER = 6;

const int DAT_SETUPFILEXFER = 7;

const int DAT_STATUS = 8;

const int DAT_USERINTERFACE = 9;

const int DAT_XFERGROUP = 10;

const int DAT_CUSTOMDSDATA = 12;

const int DAT_DEVICEEVENT = 13;

const int DAT_FILESYSTEM = 14;

const int DAT_PASSTHRU = 15;

const int DAT_CALLBACK = 16;

const int DAT_STATUSUTF8 = 17;

const int DAT_CALLBACK2 = 18;

const int DAT_METRICS = 19;

const int DAT_TWAINDIRECT = 20;

const int DAT_IMAGEINFO = 257;

const int DAT_IMAGELAYOUT = 258;

const int DAT_IMAGEMEMXFER = 259;

const int DAT_IMAGENATIVEXFER = 260;

const int DAT_IMAGEFILEXFER = 261;

const int DAT_CIECOLOR = 262;

const int DAT_GRAYRESPONSE = 263;

const int DAT_RGBRESPONSE = 264;

const int DAT_JPEGCOMPRESSION = 265;

const int DAT_PALETTE8 = 266;

const int DAT_EXTIMAGEINFO = 267;

const int DAT_FILTER = 268;

const int DAT_AUDIOFILEXFER = 513;

const int DAT_AUDIOINFO = 514;

const int DAT_AUDIONATIVEXFER = 515;

const int DAT_ICCPROFILE = 1025;

const int DAT_IMAGEMEMFILEXFER = 1026;

const int DAT_ENTRYPOINT = 1027;

const int MSG_NULL = 0;

const int MSG_CUSTOMBASE = 32768;

const int MSG_GET = 1;

const int MSG_GETCURRENT = 2;

const int MSG_GETDEFAULT = 3;

const int MSG_GETFIRST = 4;

const int MSG_GETNEXT = 5;

const int MSG_SET = 6;

const int MSG_RESET = 7;

const int MSG_QUERYSUPPORT = 8;

const int MSG_GETHELP = 9;

const int MSG_GETLABEL = 10;

const int MSG_GETLABELENUM = 11;

const int MSG_SETCONSTRAINT = 12;

const int MSG_XFERREADY = 257;

const int MSG_CLOSEDSREQ = 258;

const int MSG_CLOSEDSOK = 259;

const int MSG_DEVICEEVENT = 260;

const int MSG_OPENDSM = 769;

const int MSG_CLOSEDSM = 770;

const int MSG_OPENDS = 1025;

const int MSG_CLOSEDS = 1026;

const int MSG_USERSELECT = 1027;

const int MSG_DISABLEDS = 1281;

const int MSG_ENABLEDS = 1282;

const int MSG_ENABLEDSUIONLY = 1283;

const int MSG_PROCESSEVENT = 1537;

const int MSG_ENDXFER = 1793;

const int MSG_STOPFEEDER = 1794;

const int MSG_CHANGEDIRECTORY = 2049;

const int MSG_CREATEDIRECTORY = 2050;

const int MSG_DELETE = 2051;

const int MSG_FORMATMEDIA = 2052;

const int MSG_GETCLOSE = 2053;

const int MSG_GETFIRSTFILE = 2054;

const int MSG_GETINFO = 2055;

const int MSG_GETNEXTFILE = 2056;

const int MSG_RENAME = 2057;

const int MSG_COPY = 2058;

const int MSG_AUTOMATICCAPTUREDIRECTORY = 2059;

const int MSG_PASSTHRU = 2305;

const int MSG_REGISTER_CALLBACK = 2306;

const int MSG_RESETALL = 2561;

const int MSG_SETTASK = 2817;

const int CAP_CUSTOMBASE = 32768;

const int CAP_XFERCOUNT = 1;

const int ICAP_COMPRESSION = 256;

const int ICAP_PIXELTYPE = 257;

const int ICAP_UNITS = 258;

const int ICAP_XFERMECH = 259;

const int CAP_AUTHOR = 4096;

const int CAP_CAPTION = 4097;

const int CAP_FEEDERENABLED = 4098;

const int CAP_FEEDERLOADED = 4099;

const int CAP_TIMEDATE = 4100;

const int CAP_SUPPORTEDCAPS = 4101;

const int CAP_EXTENDEDCAPS = 4102;

const int CAP_AUTOFEED = 4103;

const int CAP_CLEARPAGE = 4104;

const int CAP_FEEDPAGE = 4105;

const int CAP_REWINDPAGE = 4106;

const int CAP_INDICATORS = 4107;

const int CAP_PAPERDETECTABLE = 4109;

const int CAP_UICONTROLLABLE = 4110;

const int CAP_DEVICEONLINE = 4111;

const int CAP_AUTOSCAN = 4112;

const int CAP_THUMBNAILSENABLED = 4113;

const int CAP_DUPLEX = 4114;

const int CAP_DUPLEXENABLED = 4115;

const int CAP_ENABLEDSUIONLY = 4116;

const int CAP_CUSTOMDSDATA = 4117;

const int CAP_ENDORSER = 4118;

const int CAP_JOBCONTROL = 4119;

const int CAP_ALARMS = 4120;

const int CAP_ALARMVOLUME = 4121;

const int CAP_AUTOMATICCAPTURE = 4122;

const int CAP_TIMEBEFOREFIRSTCAPTURE = 4123;

const int CAP_TIMEBETWEENCAPTURES = 4124;

const int CAP_MAXBATCHBUFFERS = 4126;

const int CAP_DEVICETIMEDATE = 4127;

const int CAP_POWERSUPPLY = 4128;

const int CAP_CAMERAPREVIEWUI = 4129;

const int CAP_DEVICEEVENT = 4130;

const int CAP_SERIALNUMBER = 4132;

const int CAP_PRINTER = 4134;

const int CAP_PRINTERENABLED = 4135;

const int CAP_PRINTERINDEX = 4136;

const int CAP_PRINTERMODE = 4137;

const int CAP_PRINTERSTRING = 4138;

const int CAP_PRINTERSUFFIX = 4139;

const int CAP_LANGUAGE = 4140;

const int CAP_FEEDERALIGNMENT = 4141;

const int CAP_FEEDERORDER = 4142;

const int CAP_REACQUIREALLOWED = 4144;

const int CAP_BATTERYMINUTES = 4146;

const int CAP_BATTERYPERCENTAGE = 4147;

const int CAP_CAMERASIDE = 4148;

const int CAP_SEGMENTED = 4149;

const int CAP_CAMERAENABLED = 4150;

const int CAP_CAMERAORDER = 4151;

const int CAP_MICRENABLED = 4152;

const int CAP_FEEDERPREP = 4153;

const int CAP_FEEDERPOCKET = 4154;

const int CAP_AUTOMATICSENSEMEDIUM = 4155;

const int CAP_CUSTOMINTERFACEGUID = 4156;

const int CAP_SUPPORTEDCAPSSEGMENTUNIQUE = 4157;

const int CAP_SUPPORTEDDATS = 4158;

const int CAP_DOUBLEFEEDDETECTION = 4159;

const int CAP_DOUBLEFEEDDETECTIONLENGTH = 4160;

const int CAP_DOUBLEFEEDDETECTIONSENSITIVITY = 4161;

const int CAP_DOUBLEFEEDDETECTIONRESPONSE = 4162;

const int CAP_PAPERHANDLING = 4163;

const int CAP_INDICATORSMODE = 4164;

const int CAP_PRINTERVERTICALOFFSET = 4165;

const int CAP_POWERSAVETIME = 4166;

const int CAP_PRINTERCHARROTATION = 4167;

const int CAP_PRINTERFONTSTYLE = 4168;

const int CAP_PRINTERINDEXLEADCHAR = 4169;

const int CAP_PRINTERINDEXMAXVALUE = 4170;

const int CAP_PRINTERINDEXNUMDIGITS = 4171;

const int CAP_PRINTERINDEXSTEP = 4172;

const int CAP_PRINTERINDEXTRIGGER = 4173;

const int CAP_PRINTERSTRINGPREVIEW = 4174;

const int CAP_SHEETCOUNT = 4175;

const int ICAP_AUTOBRIGHT = 4352;

const int ICAP_BRIGHTNESS = 4353;

const int ICAP_CONTRAST = 4355;

const int ICAP_CUSTHALFTONE = 4356;

const int ICAP_EXPOSURETIME = 4357;

const int ICAP_FILTER = 4358;

const int ICAP_FLASHUSED = 4359;

const int ICAP_GAMMA = 4360;

const int ICAP_HALFTONES = 4361;

const int ICAP_HIGHLIGHT = 4362;

const int ICAP_IMAGEFILEFORMAT = 4364;

const int ICAP_LAMPSTATE = 4365;

const int ICAP_LIGHTSOURCE = 4366;

const int ICAP_ORIENTATION = 4368;

const int ICAP_PHYSICALWIDTH = 4369;

const int ICAP_PHYSICALHEIGHT = 4370;

const int ICAP_SHADOW = 4371;

const int ICAP_FRAMES = 4372;

const int ICAP_XNATIVERESOLUTION = 4374;

const int ICAP_YNATIVERESOLUTION = 4375;

const int ICAP_XRESOLUTION = 4376;

const int ICAP_YRESOLUTION = 4377;

const int ICAP_MAXFRAMES = 4378;

const int ICAP_TILES = 4379;

const int ICAP_BITORDER = 4380;

const int ICAP_CCITTKFACTOR = 4381;

const int ICAP_LIGHTPATH = 4382;

const int ICAP_PIXELFLAVOR = 4383;

const int ICAP_PLANARCHUNKY = 4384;

const int ICAP_ROTATION = 4385;

const int ICAP_SUPPORTEDSIZES = 4386;

const int ICAP_THRESHOLD = 4387;

const int ICAP_XSCALING = 4388;

const int ICAP_YSCALING = 4389;

const int ICAP_BITORDERCODES = 4390;

const int ICAP_PIXELFLAVORCODES = 4391;

const int ICAP_JPEGPIXELTYPE = 4392;

const int ICAP_TIMEFILL = 4394;

const int ICAP_BITDEPTH = 4395;

const int ICAP_BITDEPTHREDUCTION = 4396;

const int ICAP_UNDEFINEDIMAGESIZE = 4397;

const int ICAP_IMAGEDATASET = 4398;

const int ICAP_EXTIMAGEINFO = 4399;

const int ICAP_MINIMUMHEIGHT = 4400;

const int ICAP_MINIMUMWIDTH = 4401;

const int ICAP_AUTODISCARDBLANKPAGES = 4404;

const int ICAP_FLIPROTATION = 4406;

const int ICAP_BARCODEDETECTIONENABLED = 4407;

const int ICAP_SUPPORTEDBARCODETYPES = 4408;

const int ICAP_BARCODEMAXSEARCHPRIORITIES = 4409;

const int ICAP_BARCODESEARCHPRIORITIES = 4410;

const int ICAP_BARCODESEARCHMODE = 4411;

const int ICAP_BARCODEMAXRETRIES = 4412;

const int ICAP_BARCODETIMEOUT = 4413;

const int ICAP_ZOOMFACTOR = 4414;

const int ICAP_PATCHCODEDETECTIONENABLED = 4415;

const int ICAP_SUPPORTEDPATCHCODETYPES = 4416;

const int ICAP_PATCHCODEMAXSEARCHPRIORITIES = 4417;

const int ICAP_PATCHCODESEARCHPRIORITIES = 4418;

const int ICAP_PATCHCODESEARCHMODE = 4419;

const int ICAP_PATCHCODEMAXRETRIES = 4420;

const int ICAP_PATCHCODETIMEOUT = 4421;

const int ICAP_FLASHUSED2 = 4422;

const int ICAP_IMAGEFILTER = 4423;

const int ICAP_NOISEFILTER = 4424;

const int ICAP_OVERSCAN = 4425;

const int ICAP_AUTOMATICBORDERDETECTION = 4432;

const int ICAP_AUTOMATICDESKEW = 4433;

const int ICAP_AUTOMATICROTATE = 4434;

const int ICAP_JPEGQUALITY = 4435;

const int ICAP_FEEDERTYPE = 4436;

const int ICAP_ICCPROFILE = 4437;

const int ICAP_AUTOSIZE = 4438;

const int ICAP_AUTOMATICCROPUSESFRAME = 4439;

const int ICAP_AUTOMATICLENGTHDETECTION = 4440;

const int ICAP_AUTOMATICCOLORENABLED = 4441;

const int ICAP_AUTOMATICCOLORNONCOLORPIXELTYPE = 4442;

const int ICAP_COLORMANAGEMENTENABLED = 4443;

const int ICAP_IMAGEMERGE = 4444;

const int ICAP_IMAGEMERGEHEIGHTTHRESHOLD = 4445;

const int ICAP_SUPPORTEDEXTIMAGEINFO = 4446;

const int ICAP_FILMTYPE = 4447;

const int ICAP_MIRROR = 4448;

const int ICAP_JPEGSUBSAMPLING = 4449;

const int ACAP_XFERMECH = 4610;

const int TWEI_BARCODEX = 4608;

const int TWEI_BARCODEY = 4609;

const int TWEI_BARCODETEXT = 4610;

const int TWEI_BARCODETYPE = 4611;

const int TWEI_DESHADETOP = 4612;

const int TWEI_DESHADELEFT = 4613;

const int TWEI_DESHADEHEIGHT = 4614;

const int TWEI_DESHADEWIDTH = 4615;

const int TWEI_DESHADESIZE = 4616;

const int TWEI_SPECKLESREMOVED = 4617;

const int TWEI_HORZLINEXCOORD = 4618;

const int TWEI_HORZLINEYCOORD = 4619;

const int TWEI_HORZLINELENGTH = 4620;

const int TWEI_HORZLINETHICKNESS = 4621;

const int TWEI_VERTLINEXCOORD = 4622;

const int TWEI_VERTLINEYCOORD = 4623;

const int TWEI_VERTLINELENGTH = 4624;

const int TWEI_VERTLINETHICKNESS = 4625;

const int TWEI_PATCHCODE = 4626;

const int TWEI_ENDORSEDTEXT = 4627;

const int TWEI_FORMCONFIDENCE = 4628;

const int TWEI_FORMTEMPLATEMATCH = 4629;

const int TWEI_FORMTEMPLATEPAGEMATCH = 4630;

const int TWEI_FORMHORZDOCOFFSET = 4631;

const int TWEI_FORMVERTDOCOFFSET = 4632;

const int TWEI_BARCODECOUNT = 4633;

const int TWEI_BARCODECONFIDENCE = 4634;

const int TWEI_BARCODEROTATION = 4635;

const int TWEI_BARCODETEXTLENGTH = 4636;

const int TWEI_DESHADECOUNT = 4637;

const int TWEI_DESHADEBLACKCOUNTOLD = 4638;

const int TWEI_DESHADEBLACKCOUNTNEW = 4639;

const int TWEI_DESHADEBLACKRLMIN = 4640;

const int TWEI_DESHADEBLACKRLMAX = 4641;

const int TWEI_DESHADEWHITECOUNTOLD = 4642;

const int TWEI_DESHADEWHITECOUNTNEW = 4643;

const int TWEI_DESHADEWHITERLMIN = 4644;

const int TWEI_DESHADEWHITERLAVE = 4645;

const int TWEI_DESHADEWHITERLMAX = 4646;

const int TWEI_BLACKSPECKLESREMOVED = 4647;

const int TWEI_WHITESPECKLESREMOVED = 4648;

const int TWEI_HORZLINECOUNT = 4649;

const int TWEI_VERTLINECOUNT = 4650;

const int TWEI_DESKEWSTATUS = 4651;

const int TWEI_SKEWORIGINALANGLE = 4652;

const int TWEI_SKEWFINALANGLE = 4653;

const int TWEI_SKEWCONFIDENCE = 4654;

const int TWEI_SKEWWINDOWX1 = 4655;

const int TWEI_SKEWWINDOWY1 = 4656;

const int TWEI_SKEWWINDOWX2 = 4657;

const int TWEI_SKEWWINDOWY2 = 4658;

const int TWEI_SKEWWINDOWX3 = 4659;

const int TWEI_SKEWWINDOWY3 = 4660;

const int TWEI_SKEWWINDOWX4 = 4661;

const int TWEI_SKEWWINDOWY4 = 4662;

const int TWEI_BOOKNAME = 4664;

const int TWEI_CHAPTERNUMBER = 4665;

const int TWEI_DOCUMENTNUMBER = 4666;

const int TWEI_PAGENUMBER = 4667;

const int TWEI_CAMERA = 4668;

const int TWEI_FRAMENUMBER = 4669;

const int TWEI_FRAME = 4670;

const int TWEI_PIXELFLAVOR = 4671;

const int TWEI_ICCPROFILE = 4672;

const int TWEI_LASTSEGMENT = 4673;

const int TWEI_SEGMENTNUMBER = 4674;

const int TWEI_MAGDATA = 4675;

const int TWEI_MAGTYPE = 4676;

const int TWEI_PAGESIDE = 4677;

const int TWEI_FILESYSTEMSOURCE = 4678;

const int TWEI_IMAGEMERGED = 4679;

const int TWEI_MAGDATALENGTH = 4680;

const int TWEI_PAPERCOUNT = 4681;

const int TWEI_PRINTERTEXT = 4682;

const int TWEI_TWAINDIRECTMETADATA = 4683;

const int TWEJ_NONE = 0;

const int TWEJ_MIDSEPARATOR = 1;

const int TWEJ_PATCH1 = 2;

const int TWEJ_PATCH2 = 3;

const int TWEJ_PATCH3 = 4;

const int TWEJ_PATCH4 = 5;

const int TWEJ_PATCH6 = 6;

const int TWEJ_PATCHT = 7;

const int TWRC_CUSTOMBASE = 32768;

const int TWRC_SUCCESS = 0;

const int TWRC_FAILURE = 1;

const int TWRC_CHECKSTATUS = 2;

const int TWRC_CANCEL = 3;

const int TWRC_DSEVENT = 4;

const int TWRC_NOTDSEVENT = 5;

const int TWRC_XFERDONE = 6;

const int TWRC_ENDOFLIST = 7;

const int TWRC_INFONOTSUPPORTED = 8;

const int TWRC_DATANOTAVAILABLE = 9;

const int TWRC_BUSY = 10;

const int TWRC_SCANNERLOCKED = 11;

const int TWCC_CUSTOMBASE = 32768;

const int TWCC_SUCCESS = 0;

const int TWCC_BUMMER = 1;

const int TWCC_LOWMEMORY = 2;

const int TWCC_NODS = 3;

const int TWCC_MAXCONNECTIONS = 4;

const int TWCC_OPERATIONERROR = 5;

const int TWCC_BADCAP = 6;

const int TWCC_BADPROTOCOL = 9;

const int TWCC_BADVALUE = 10;

const int TWCC_SEQERROR = 11;

const int TWCC_BADDEST = 12;

const int TWCC_CAPUNSUPPORTED = 13;

const int TWCC_CAPBADOPERATION = 14;

const int TWCC_CAPSEQERROR = 15;

const int TWCC_DENIED = 16;

const int TWCC_FILEEXISTS = 17;

const int TWCC_FILENOTFOUND = 18;

const int TWCC_NOTEMPTY = 19;

const int TWCC_PAPERJAM = 20;

const int TWCC_PAPERDOUBLEFEED = 21;

const int TWCC_FILEWRITEERROR = 22;

const int TWCC_CHECKDEVICEONLINE = 23;

const int TWCC_INTERLOCK = 24;

const int TWCC_DAMAGEDCORNER = 25;

const int TWCC_FOCUSERROR = 26;

const int TWCC_DOCTOOLIGHT = 27;

const int TWCC_DOCTOODARK = 28;

const int TWCC_NOMEDIA = 29;

const int TWQC_GET = 1;

const int TWQC_SET = 2;

const int TWQC_GETDEFAULT = 4;

const int TWQC_GETCURRENT = 8;

const int TWQC_RESET = 16;

const int TWQC_SETCONSTRAINT = 32;

const int TWQC_CONSTRAINABLE = 64;

const int TWQC_GETHELP = 256;

const int TWQC_GETLABEL = 512;

const int TWQC_GETLABELENUM = 1024;

const int TWTY_STR1024 = 13;

const int TWTY_UNI512 = 14;

const int TWFF_JPN = 12;

const int DAT_TWUNKIDENTITY = 11;

const int DAT_SETUPFILEXFER2 = 769;

const int CAP_CLEARBUFFERS = 4125;

const int CAP_SUPPORTEDCAPSEXT = 4108;

const int CAP_PAGEMULTIPLEACQUIRE = 4131;

const int CAP_PAPERBINDING = 4143;

const int CAP_PASSTHRU = 4145;

const int CAP_POWERDOWNTIME = 4148;

const int ACAP_AUDIOFILEFORMAT = 4609;

const int MSG_CHECKSTATUS = 513;

const int MSG_INVOKE_CALLBACK = 2307;

const int TWSX_FILE2 = 3;

const int TWFS_FILESYSTEM = 0;

const int TWFS_RECURSIVEDELETE = 1;

const int TWPT_SRGB64 = 11;

const int TWPT_BGR = 12;

const int TWPT_CIELAB = 13;

const int TWPT_CIELUV = 14;

const int TWPT_YCBCR = 15;

const int TWSS_B = 8;

const int TWSS_A4LETTER = 1;

const int TWSS_B3 = 12;

const int TWSS_B4 = 6;

const int TWSS_B6 = 7;

const int TWSS_B5LETTER = 2;

const int TWAF_WAV = 0;

const int TWAF_AIFF = 1;

const int TWAF_AU = 3;

const int TWAF_SND = 4;

const int TWCB_AUTO = 0;

const int TWCB_CLEAR = 1;

const int TWCB_NOCLEAR = 2;

typedef _c_DSM_Entry = ffi.Uint16 Function(
  ffi.Pointer<TW_IDENTITY> pOrigin,
  ffi.Pointer<TW_IDENTITY> pDest,
  ffi.Uint32 DG,
  ffi.Uint16 DAT,
  ffi.Uint16 MSG,
  ffi.Pointer<ffi.Void> pData,
);

typedef _dart_DSM_Entry = int Function(
  ffi.Pointer<TW_IDENTITY> pOrigin,
  ffi.Pointer<TW_IDENTITY> pDest,
  int DG,
  int DAT,
  int MSG,
  ffi.Pointer<ffi.Void> pData,
);

typedef _c_DS_Entry = ffi.Uint16 Function(
  ffi.Pointer<TW_IDENTITY> pOrigin,
  ffi.Uint32 DG,
  ffi.Uint16 DAT,
  ffi.Uint16 MSG,
  ffi.Pointer<ffi.Void> pData,
);

typedef _dart_DS_Entry = int Function(
  ffi.Pointer<TW_IDENTITY> pOrigin,
  int DG,
  int DAT,
  int MSG,
  ffi.Pointer<ffi.Void> pData,
);

typedef _c_TWAIN_Callback = ffi.Uint16 Function(
  ffi.Pointer<TW_IDENTITY> pOrigin,
  ffi.Pointer<TW_IDENTITY> pDest,
  ffi.Uint32 DG,
  ffi.Uint16 DAT,
  ffi.Uint16 MSG,
  ffi.Pointer<ffi.Void> pData,
);

typedef _dart_TWAIN_Callback = int Function(
  ffi.Pointer<TW_IDENTITY> pOrigin,
  ffi.Pointer<TW_IDENTITY> pDest,
  int DG,
  int DAT,
  int MSG,
  ffi.Pointer<ffi.Void> pData,
);

typedef _c_DSM_MemAllocate = ffi.Pointer<ffi.Void> Function(
  ffi.Uint32 arg0,
);

typedef _dart_DSM_MemAllocate = ffi.Pointer<ffi.Void> Function(
  int arg0,
);

typedef _c_DSM_MemFree = ffi.Void Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _dart_DSM_MemFree = void Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _c_DSM_MemLock = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _dart_DSM_MemLock = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _c_DSM_MemUnlock = ffi.Void Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _dart_DSM_MemUnlock = void Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef DSMENTRYPROC = ffi.Uint16 Function(
  ffi.Pointer<TW_IDENTITY>,
  ffi.Pointer<TW_IDENTITY>,
  ffi.Uint32,
  ffi.Uint16,
  ffi.Uint16,
  ffi.Pointer<ffi.Void>,
);

typedef DSM_MEMALLOCATE = ffi.Pointer<ffi.Void> Function(
  ffi.Uint32,
);

typedef DSM_MEMFREE = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
);

typedef DSM_MEMLOCK = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void>,
);

typedef DSM_MEMUNLOCK = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
);
