// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `user32.h`.
class User32 {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  User32(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  ffi.Pointer<HWND> GetDesktopWindow() {
    return (_GetDesktopWindow ??=
        _dylib.lookupFunction<_c_GetDesktopWindow, _dart_GetDesktopWindow>(
            'GetDesktopWindow'))();
  }

  _dart_GetDesktopWindow? _GetDesktopWindow;
}

class HWND extends ffi.Struct {
  @ffi.Int32()
  external int unused;
}

typedef _c_GetDesktopWindow = ffi.Pointer<HWND> Function();

typedef _dart_GetDesktopWindow = ffi.Pointer<HWND> Function();
